### ISSUE TITLE
Catalog fails to export photographs, shows this error in the console [Quilt 1.20.1]

### ISSUE THREAD

**Issue by ghost** [mortuusars/ExposureCatalog#2]
Uncaught exception in thread "Thread-165"
java.lang.NoClassDefFoundError: net/minecraft/class_1011
        at io.github.mortuusars.exposure.data.storage.ExposureExporter.convertToNativeImage(ExposureExporter.java:123) ~[exposure-1.7.2.i0:0/:?]
        at io.github.mortuusars.exposure.data.storage.ExposureExporter.save(ExposureExporter.java:79) ~[exposure-1.7.2.i0:0/:?]
        at io.github.mortuusars.exposure.data.storage.ExposureExporter.save(ExposureExporter.java:75) ~[exposure-1.7.2.i0:0/:?]
        at io.github.mortuusars.exposure_catalog.network.handler.ServerPacketsHandler.exportExposuresChunk(ServerPacketsHandler.java:112) ~[exposure-catalog-1.0.0.i0:0/:?]
        at io.github.mortuusars.exposure_catalog.network.handler.ServerPacketsHandler.lambda$exportExposuresChunk$0(ServerPacketsHandler.java:73) ~[exposure-catalog-1.0.0.i0:0/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1011
        ... 6 more
[11:00:56] [Thread-164/INFO]: Exported 0 exposures.

**Comment by mortuusars** [comment]
Fixed in 1.0.1.
